#   Portions Copyright (c) 2000 by Virtutech AB.
#
#   Permission to use, copy, modify, and distribute this software
#   for any purpose with or without fee is hereby granted, provided
#   that the above copyright notice and this permission notice appear
#   in all copies, and that the name of Virtutech AB not be used in
#   advertising or publicity pertaining to distribution of the document
#   or software without specific, written prior permission.
#
#   THE SOFTWARE IS PROVIDED "AS IS" AND VIRTUTECH AB DISCLAIMS ALL
#   WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED
#   WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL 
#   VIRTUTECH AB BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
#   CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
#   LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
#   NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
#   CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

MODULE_DIR = emerald
MODULE_NAME = emerald
FILENAME = emerald

# For Simics 2.X
#GEMS_ROOT = $(SIMICS_BASE)/../

# For Simics 3.0
GEMS_ROOT = $(SRC_BASE)/../../

include $(GEMS_ROOT)/common/Makefile.simics_version

MODULE_CFLAGS += -DTARGET_VA_BITS=64 -DTARGET_PA_BITS=64
MODULE_LDFLAGS += -ggdb -g3

ifeq ($(SIMICS_VERSION),2.0.X)
  MODULE_CFLAGS += -DSIMICS_2_0
  SIMICS_API = 2.0
  # NOTE: Don't place .a files in EXTRA_OBJ_FILES
  EXTRA_OBJ_FILES = $(shell ls -1 $(SIMICS_BASE)/../emerald/$(HOST_TYPE)/obj/*.o | grep -v simdist12.o | grep -v memscan.o |\
				   	grep -v makeipage.o | grep -v readipage.o | grep -v usd.o | grep -v regtest.o | grep -v simmain.o | \
					grep -v bp.o | grep -v ptracetest.o | tr '\n' ' ')
  CALC_HOST = $(SIMICS_BASE)/../scripts/calc_host.sh
else
ifeq ($(SIMICS_VERSION),2.2.X)
  MODULE_CFLAGS += -DSIMICS_2_2
  SIMICS_API = 2.0
  # NOTE: Don't place .a files in EXTRA_OBJ_FILES
  EXTRA_OBJ_FILES = $(shell ls -1 $(SIMICS_BASE)/../emerald/$(HOST_TYPE)/obj/*.o | grep -v simdist12.o | grep -v memscan.o |\
				   	grep -v makeipage.o | grep -v readipage.o | grep -v usd.o | grep -v regtest.o | grep -v simmain.o | \
					grep -v bp.o | grep -v ptracetest.o | tr '\n' ' ')
  CALC_HOST = $(SIMICS_BASE)/../scripts/calc_host.sh
else
ifeq ($(SIMICS_VERSION),3.0)
  MODULE_CFLAGS += -DADD_ARCH_TO_API -DSIMICS_3_0 
  SIMICS_API = 3.0
  EXTRA_OBJ_FILES = $(shell ls -1 $(SRC_BASE)/../../emerald/$(HOST_TYPE)/obj/*.o | grep -v simdist12.o | grep -v memscan.o |\
				   	grep -v makeipage.o | grep -v readipage.o | grep -v usd.o | grep -v regtest.o | grep -v simmain.o | \
					grep -v bp.o | grep -v ptracetest.o | tr '\n' ' ')
  CALC_HOST = $(SRC_BASE)/../../scripts/calc_host.sh
else
  # This will stop compilation with an error
  MODULE_CFLAGS += UNKNOWN_SIMICS_VERSION
endif
endif
endif


# Optioally, you can specify which library path being written into the object
# Normally, you don't need this
#MODULE_LDFLAGS += -Wl,-R/your/lib/path

# Control whether we link in gcc and stdc++ libraries or not.
# In fact, simics Makefile has had a "-shared" in front of us, so we are
# overwritting their linking parameters.
#MODULE_LDFLAGS += -Wl,-Bstatic -lstdc++ -static-libgcc
MODULE_LDFLAGS += -Wl,-Bdynamic -lstdc++ -shared-libgcc

EXTRA_VPATH = $(SIMICS_BASE)/../emerald/common:$(SIMICS_BASE)/../emerald/system:$(SIMICS_BASE)/../emerald/benchmark/tester:$(SIMICS_BASE)/$(HOST_TYPE)/obj/include/simics

# For SUNWspro compiler
#MODULE_LDFLAGS = -staticlib=Cstd

LDFLAGS_DYN = 

SRC_FILES = emerald.c

MODULE_ARCHS = sun4u

MODULE_CLASSES = emerald

ifeq ($(SIMICS_VERSION),2.0.X)
  INCLUDE_FILENAME := $(SIMICS_BASE)/src/devices/common/device-makefile
  EXTRA_VPATH = $(SIMICS_BASE)/../emerald:$(SIMICS_BASE)/../emerald/common:$(SIMICS_BASE)/../emerald/system:$(SIMICS_BASE)/../emerald/benchmark/tester:$(SIMICS_BASE)/$(HOST_TYPE)/obj/include/simics
else
ifeq ($(SIMICS_VERSION),2.2.X)
  INCLUDE_FILENAME := $(SIMICS_BASE)/src/devices/common/device-makefile
  EXTRA_VPATH = $(SIMICS_BASE)/../emerald:$(SIMICS_BASE)/../emerald/common:$(SIMICS_BASE)/../emerald/system:$(SIMICS_BASE)/../emerald/benchmark/tester:$(SIMICS_BASE)/$(HOST_TYPE)/obj/include/simics
else
ifeq ($(SIMICS_VERSION),3.0)
  INCLUDE_FILENAME := $(MODULE_MAKEFILE)
  EXTRA_VPATH = $(SRC_BASE)/../../emerald:$(GEMS_ROOT)/simics-3.0.31/src/include/simics
else
  INCLUDE_FILENAME := UNKNOWN_SIMICS_VERSION
endif
endif
endif

include $(INCLUDE_FILENAME)

